# Generated by Django 5.1.7 on 2025-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhealthdata",
            name="calories",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
