# Generated by Django 5.1.7 on 2025-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_dailyhealthdata_calories"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhealthdata",
            name="activity_minutes",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
